FROM openjdk:17

ARG PROFILE
ENV PROFILE=$PROFILE

ARG DB_USERNAME
ENV DB_USERNAME=$DB_USERNAME

ARG DB_PASSWORD
ENV DB_PASSWORD=$DB_PASSWORD

ARG DB_URL
ENV DB_URL=$DB_URL

ARG REDIS_PORT
ENV REDIS_PORT=$REDIS_PORT

ARG REDIS_HOST
ENV REDIS_HOST=$REDIS_HOST

ARG MAIL_USERNAME
ENV MAIL_USERNAME=$MAIL_USERNAME

ARG MAIL_PASSWORD
ENV MAIL_PASSWORD=$MAIL_PASSWORD

ARG JWT_SECRET_KEY
ENV JWT_SECRET_KEY=$JWT_SECRET_KEY

ARG JWT_ACCESS_EXP
ENV JWT_ACCESS_EXP=$JWT_ACCESS_EXP

ARG JWT_REFRESH_EXP
ENV JWT_REFRESH_EXP=$JWT_REFRESH_EXP

ARG JWT_HEADER
ENV JWT_HEADER=$JWT_HEADER

ARG JWT_PREFIX
ENV JWT_PREFIX=$JWT_PREFIX

ARG GPT_SECRET
ENV GPT_SECRET=$GPT_SECRET

ARG AWS_ACCESS_KEY_ID
ENV AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID

ARG AWS_SECRET_ACCESS_KEY
ENV AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY

ARG SEGMENTS_ID
ENV SEGMENTS_ID=$SEGMENTS_ID

ARG FLARELANE_API_KEY
ENV FLARELANE_API_KEY=$FLARELANE_API_KEY

COPY build/libs/mukgen-0.0.1-SNAPSHOT.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]